apiVersion: v1
name: sunnydale
metadata:
  name: gcp
kind: values
resource: gcp
values:
  name: us-central1-test
  resource:
    project: still-entity-201400
  cluster:
    name: us-central1-test
    location: us-central1
    region: us-central1
    zone: us-central1-a
  network:
    holepunch: 22223
  registry:
    update: us-central1-test
  environment:
    openrc: 
    mexenv: https://vault.mobiledgex.net/v1/secret/data/cloudlet/openstack/mexenv.json
