vault_user: vault
vault_group: vault
vault_path: /usr/local/bin
vault_conf: /etc/vault.hcl
vault_plugin_directory: /etc/vault-plugins
vault_audit_log: /var/log/vault_audit.log
vault_logrotate_path: /etc/logrotate.d/vault
certgen_image: "{{ mex_docker_registry }}/mobiledgex/certgen"
certgen_port: 4568
certgen_volume: letsencrypt_certs
github_policy: github-dev
github_org: mobiledgex
github_dev_team: edge-cloud-development-team
vault_status_monitor_plugin: /usr/local/bin/vault-status-monitor.py
